# Generated by Django 4.0.4 on 2022-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname_artist', models.TextField(blank=True, db_column='musicname & artist', null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('rms_mean', models.FloatField(blank=True, null=True)),
                ('rms_var', models.FloatField(blank=True, null=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('zero_crossing_rate_mean', models.FloatField(blank=True, null=True)),
                ('zero_crossing_rate_var', models.FloatField(blank=True, null=True)),
                ('harmony_mean', models.FloatField(blank=True, null=True)),
                ('harmony_var', models.FloatField(blank=True, null=True)),
                ('percussive_mean', models.FloatField(blank=True, null=True)),
                ('percussive_var', models.FloatField(blank=True, null=True)),
                ('spectral_centroid_mean', models.FloatField(blank=True, null=True)),
                ('spectral_centroid_var', models.FloatField(blank=True, null=True)),
                ('spectral_bandwidth_mean', models.FloatField(blank=True, null=True)),
                ('spectral_bandwidth_var', models.FloatField(blank=True, null=True)),
                ('spectral_rolloff_mean', models.FloatField(blank=True, null=True)),
                ('spectral_rolloff_var', models.FloatField(blank=True, null=True)),
                ('chroma_frequencies_mean', models.FloatField(blank=True, null=True)),
                ('chroma_frequencies_var', models.FloatField(blank=True, null=True)),
                ('mfcc1_mean', models.FloatField(blank=True, null=True)),
                ('mfcc1_var', models.FloatField(blank=True, null=True)),
                ('mfcc2_mean', models.FloatField(blank=True, null=True)),
                ('mfcc2_var', models.FloatField(blank=True, null=True)),
                ('mfcc3_mean', models.FloatField(blank=True, null=True)),
                ('mfcc3_var', models.FloatField(blank=True, null=True)),
                ('mfcc4_mean', models.FloatField(blank=True, null=True)),
                ('mfcc4_var', models.FloatField(blank=True, null=True)),
                ('mfcc5_mean', models.FloatField(blank=True, null=True)),
                ('mfcc5_var', models.FloatField(blank=True, null=True)),
                ('mfcc6_mean', models.FloatField(blank=True, null=True)),
                ('mfcc6_var', models.FloatField(blank=True, null=True)),
                ('mfcc7_mean', models.FloatField(blank=True, null=True)),
                ('mfcc7_var', models.FloatField(blank=True, null=True)),
                ('mfcc8_mean', models.FloatField(blank=True, null=True)),
                ('mfcc8_var', models.FloatField(blank=True, null=True)),
                ('mfcc9_mean', models.FloatField(blank=True, null=True)),
                ('mfcc9_var', models.FloatField(blank=True, null=True)),
                ('mfcc10_mean', models.FloatField(blank=True, null=True)),
                ('mfcc10_var', models.FloatField(blank=True, null=True)),
                ('mfcc11_mean', models.FloatField(blank=True, null=True)),
                ('mfcc11_var', models.FloatField(blank=True, null=True)),
                ('mfcc12_mean', models.FloatField(blank=True, null=True)),
                ('mfcc12_var', models.FloatField(blank=True, null=True)),
                ('mfcc13_var', models.FloatField(blank=True, null=True)),
                ('mfcc14_mean', models.FloatField(blank=True, null=True)),
                ('mfcc14_var', models.FloatField(blank=True, null=True)),
                ('mfcc15_mean', models.FloatField(blank=True, null=True)),
                ('mfcc16_mean', models.FloatField(blank=True, null=True)),
                ('mfcc16_var', models.FloatField(blank=True, null=True)),
                ('mfcc17_mean', models.FloatField(blank=True, null=True)),
                ('mfcc17_var', models.FloatField(blank=True, null=True)),
                ('mfcc18_mean', models.FloatField(blank=True, null=True)),
                ('mfcc18_var', models.FloatField(blank=True, null=True)),
                ('mfcc19_mean', models.FloatField(blank=True, null=True)),
                ('mfcc19_var', models.FloatField(blank=True, null=True)),
                ('mfcc20_mean', models.FloatField(blank=True, null=True)),
                ('mfcc20_var', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project dataset',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Inputmusic',
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'managed': False},
        ),
    ]
