# Generated by Django 4.0.4 on 2022-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarmusic', '0007_dataset_delete_projectdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
