# Generated by Django 4.0.4 on 2022-05-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarmusic', '0008_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='music_title',
        ),
    ]
