# Generated by Django 4.0.4 on 2022-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarmusic', '0009_rename_title_music_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
